### ISSUE TITLE
Frosty Mod Manager 1.05 is still incompatible with Mass Effect Andromeda v1.10

### ISSUE THREAD

**Issue by Ghecko166** [GalaxyEham/FrostyToolSuite#157] opened 2019-04-14 08:41 UTC
I was disappointed to see that this new version (1.0.5) of Frosty Mod Manager is still not compatible with Mass Effect Andromeda v1.10.
As many users have reported, the last version of Frosty Mod Manager that was compatible with Mass Effect Andromeda v1.10 is FMM v1.0.3.1. Even version v1.0.3.1 breaks mods in specific areas of the game (cutscenes in Nexus and Kedara)

The compatibility issues are not related to a specific hardware configuration or Windows version. I've read posts where users describe the same issues with Windows 7, 8 and 10 and many different hardware setups.

Some more details: 
(these issues probably apply to all versions of Frosty Mod Manager after v1.0.3.1)

- Inability to launch the MEA game executable from inside FMM (the MEA executable appears in the Windows process viewer, but it's not running - no loading screen, no visible window)

- Inability to install mods in MEA without manually elevating the privileges of the FMM executable

- reinstalling/repairing the game does not solve the issue

- updating Windows C++ libraries and graphics drivers does not solve the issue

- manually installing the library **Bcrypt.dll from v1.0.2b** does not solve the issue

- a post with a far more detailed description of the FMM issues (and how to get version 1.0.3.1 to work) with Mass Effect Andromeda v1.10 can be found here:

(https://www.nexusmods.com/masseffectandromeda/mods/224/?tab=bugs&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fmasseffectandromeda%2Fajax%2Fmoddescription%2F%3Fid%3D224%26preview%3D1)

An excerpt from the post:

> 1 - v1.0.3.1 appears to be the only version of either Frosty Mod Manager or Frosty Editor that's compatible with MEA v1.10.
> 
> 2 - After setting everything up for Frosty Mod Manager (i.e. setting up the mods to be used in a specific folder, importing them, setting the order that will still require some guess work for most people if they're using a fair amount of mods like myself), THE MOST IMPORTANT THING TO DO IS:
> 
>  **Run Frosty Editor v1.0.3.1 with Frosty Mod Manager open. ( I had NOT previously completed this particular step, and it was the cause of most of the issues I was having. )**
> 
> _Regardless of which mod I use, how many of them I use, or if I only use one at a time the game crashes during any dialogues and cutscenes taking place on either the Nexus or Kedara._
> 
> If I launch the game using FMM with a "No Mods" profile; everything works perfectly.

**Comment by GalaxyEham** [comment] 2019-04-18 22:45
It is compatible with MEA 1.10. It has been thoroughly tested against it and will be closing this as you did not read or follow the pinned note.

**Closed by GalaxyEham** 2019-04-18 22:45 UTC

**Comment by Ghecko166** [comment] 2019-04-19 09:08
I have tested MEA v1.10 with FFM 1.0.5 two days ago, and I can assure you that FFM 1.0.5 is not compatible with it. All the issues I described are there. If you want to ignore them, that's your prerogative.

**Comment by GalaxyEham** [comment] 2019-04-19 09:33
I tested it today and I can assure you it is compatible. What you mean to say, is that your having issues with it and have decided that the issue is with the tool and not your configuration with no proof to the contrary, where as I have had numerous such reports solved by them fixing their end.

So I am absolutely not ignoring the issue, you are however ignoring the big stickied item that says "Fill out the template or I will close your issue"

**Comment by GalaxyEham** [comment] 2019-04-19 09:38
And honestly what do you expect me to be able to do without a replicatable case? You told me it was not compatible, So I ran it on Windows 10, compatible. Ran it on Windows 7. compatible. Not much more I can do at this point, everywhere i run it, it works. So the onerous is on you to provide proof

**Comment by GalaxyEham** [comment] 2019-04-19 09:38
After you fill out the template and submit a new problem as per instructions.
